language: node_js
node_js:
- '8'
- '10'
install: npm ci
script: npm run test:ci
deploy:
  - provider: npm
    email: lynxysscz@gmail.com
    api_key:
      secure: s/UQDvQwyF69iRr85f76SCjsYh7DiMosSPdY6pmNjLjc15em/Osn9vdQ8XMRdrdQ4YauEH5S+QztybsHhQVrwOOnMsxBMEuc/GZxzZPOEIGzqo4arNHrPw4ykDJYUWMTZBI1sx29p068ouJvHQnIVy8/jHMwUIeAypTyLRoTSjjdAsCY61Qvtj5RpcqdTO5Fd0MXESQQNj7XRmKp/hEfUJzzv2JmWgaolG9IyYAyUKeOEqbH2mW82Ot8vSl7TWwFULSfmFjSWD/n5Iex6inTo3psQh9sIitU0+ZA2DskV5qWn8rXwA2dqs8hj3v/nFKwoXjoc3k+/ZSfVOfn5o5IAq187YEAdXrZPB2DOEzrxNEpNfemfF7WhaOv3iZ/ztWpSkyzterOvWjRLCX1ljVO6Me3UXV8XlizOCTD/ZoX92KTO4NtmwliXP0Ko717O+X121iCJsDCgwxH0/c/63ElCIzm6MWe28/VHdhUvXy8qzWalEYbmzrOu7kg0YPDmz1ymTaqdN9INSCz3qdyEkqneFfdQMjDHTrmZCZTNMrykeUqpKXKBwL21f9gJKrGFQUEf2X54Wv+nEB0r1Ie5WSdXsFFbFKY0lPDs8Ggr9xICA52ElVsuwzD1OIAPkTMWQjOYbIJ+q7PjlU1fIxsOK+wCvuQYzUf/dSHJVfTgjHqqpE=
    skip_cleanup: true
    on:
      repo: LynxyssCZ/mapromise
      tags: true
