language: node_js
node_js:
- '6'
- '8'
deploy:
  - provider: npm
    email: lynxysscz@gmail.com
    api_key:
      secure: "NJaqisxZMkVsbAe/5OZyH9QR1O530IpYokNGE++HSIwlTaAOg1ifUazSIJgarsHf6ZeXOMqaxMxmkTD2J0Pr6XMP7yXl5zUsN47EjKxIZiP5aDRsBsJuLpBEoI3KzZEQCMFu5kwMNfkIDe9H7gUiRfCCFb7ZJtXmJchvGVoYZ0VDsglVLE36EL1ZxPr8fCE+C0/cynU0fN/9SkVJcKUlEtoszXQA2lrNLTVcBsAnZ5XnUpVGx4cmVSaGDlzvIf2xuhWp1IHrUHsVpL1UfV4Jdkk0HOef63Yrr+QTPoOMTGvXRp/xteu89JNv7M1di7sNUw6TyNvCuScX8csP8ijQwKYYULtVe0z+PbfbPB0U+kCGv/UstcJ9E4R0PHFPvrqT1U0AdTqCGRWFX3WHao33noZt100wD1bBvSdbgAtNnKr/VtgNrlcXhRY0LhxYlY0keLfETjFccgVFiiKBoS+JjkE/I5ZuRCkqoE5HRboy+BSvFrWwyfqG+8BVxnRrDPXmok+zAG19gBPm+CK0dNYzxnBxorDt3JahvcxdrSbBGsAWN14dXasl5pIimn5TbD6/O9pKYlcfD+UeCJtedfvOq8Sj/qBS0r5gGG3EumC5vXo94Y0MtM9uNVygF2D//OzY7irZj/NGJlXQ1f8Fndmibg63NjE87ryb27bZgDuVaIY="
    skip_cleanup: true
    on:
      repo: LynxyssCZ/mapromise
      tags: true
